site_name: tesswcs
nav:
    - Home: README.md
    - How to use tesswcs: tutorial.md
    - Finding where and when targets are observable: tutorial2.md
    - Mapping TESS's view of the sky: tutorial3.md
    - About tesswcs: about.md

theme:
  name: "material"
  icon:
      logo: material/globe-model
  palette:
    scheme: default
    primary: red
    accent: blue
repo_url: https://github.com/christinahedges/tesswcs
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences